class Mocks:
    """
    This class contains mocked data representing the data returned from the ABR and NRDB APIs.
    """
    RUNNER = {
        "imageUrlTemplate": "https://static.nrdbassets.com/v1/large/{code}.jpg",
        "data": [
            {
                "base_link": 0,
                "code": "26066",
                "deck_limit": 1,
                "faction_code": "anarch",
                "faction_cost": 0,
                "flavor": "Please, let me have this dream.\nFlip side:\nI'm going to be my own kind of hero.",
                "illustrator": "Luminita Pham",
                "influence_limit": 15,
                "keywords": "Natural",
                "minimum_deck_size": 45,
                "pack_code": "ur",
                "position": 66,
                "quantity": 3,
                "side_code": "runner",
                "stripped_text": "When your turn ends, if you accessed at least 1 card this turn, gain 2 credits and flip this identity. Flip side: When your turn begins, draw 1 card and lose 1 credit. When your turn ends, if you did not access at least 1 card this turn, flip this identity.",
                "stripped_title": "Hoshiko Shiro: Untold Protagonist",
                "text": "When your turn ends, if you accessed at least 1 card this turn, gain 2[credit] and flip this identity.\nFlip side:\nWhen your turn begins, draw 1 card and lose 1[credit].\nWhen your turn ends, if you did not access at least 1 card this turn, flip this identity.",
                "title": "Hoshiko Shiro: Untold Protagonist",
                "type_code": "identity",
                "uniqueness": False
            }
        ],
        "total": 1,
        "success": True,
        "version_number": "2.0",
        "last_updated": "2021-03-13T05:08:22+00:00"
    }

    CORP = {
        "imageUrlTemplate": "https://static.nrdbassets.com/v1/large/{code}.jpg",
        "data": [
            {
                "code": "21054",
                "deck_limit": 1,
                "faction_code": "nbn",
                "faction_cost": 0,
                "illustrator": "Emilio Rodriguez",
                "influence_limit": 15,
                "keywords": "Division",
                "minimum_deck_size": 40,
                "pack_code": "cotc",
                "position": 54,
                "quantity": 3,
                "side_code": "corp",
                "stripped_text": "When your turn ends, you may name a card type. Gain 2 credits the first time each turn the Runner plays or installs a card that has the type you last named this way.",
                "stripped_title": "Azmari EdTech: Shaping the Future",
                "text": "When your turn ends, you may name a card type. Gain 2[credit] the first time each turn the Runner plays or installs a card that has the type you last named this way.",
                "title": "Azmari EdTech: Shaping the Future",
                "type_code": "identity",
                "uniqueness": False
            }
        ],
        "total": 1,
        "success": True,
        "version_number": "2.0",
        "last_updated": "2021-03-13T05:08:22+00:00"
    }

    DECK = {
        "id": 1580775,
        "uuid": "a80f818b-70a5-42bb-ad1a-557e4c88b0e2",
        "date_creation": "2023-09-12T23:49:25+00:00",
        "date_update": "2023-09-19T22:12:27+00:00",
        "name": "A Glacial Teia (3rd @ West Coast Nats)",
        "description": "deck description",
        "mwl_code": "standard-ban-list-23-08",
        "cards": {
            "21039": 3,
            "21051": 3,
            "21080": 3,
            "22039": 2,
            "22041": 2,
            "26040": 1,
            "26044": 2,
            "26063": 2,
            "27005": 2,
            "28006": 3,
            "30039": 2,
            "30040": 3,
            "30053": 3,
            "30067": 3,
            "30071": 2,
            "30075": 3,
            "31081": 2,
            "33047": 2,
            "33109": 3,
            "34039": 1,
            "34044": 3
        },
        "tags": "jinteki"
    }

    DECKLIST = {
        "id": 77501,
        "uuid": "3753cd7d-49ad-4e15-9612-093a2333f496",
        "date_creation": "2023-09-19T22:13:34+00:00",
        "date_update": "2023-10-09T10:47:13+00:00",
        "name": "A Glacial Teia (3rd @ West Coast Nats)",
        "description": "decklist description",
        "user_id": 42980,
        "user_name": "Tak",
        "tournament_badge": True,
        "cards": {
            "21039": 3,
            "21051": 3,
            "21080": 3,
            "22039": 2,
            "22041": 2,
            "26040": 1,
            "26044": 2,
            "26063": 2,
            "27005": 2,
            "28006": 3,
            "30039": 2,
            "30040": 3,
            "30053": 3,
            "30067": 3,
            "30071": 2,
            "30075": 3,
            "31081": 2,
            "33047": 2,
            "33109": 3,
            "34039": 1,
            "34044": 3
        },
        "mwl_code": "standard-ban-list-23-08"
    }

    FACTIONS = [
        {
            "code": "anarch",
            "color": "FF4500",
            "is_mini": False,
            "name": "Anarch",
            "side_code": "runner"
        },
        {
            "code": "criminal",
            "color": "4169E1",
            "is_mini": False,
            "name": "Criminal",
            "side_code": "runner"
        },
        {
            "code": "shaper",
            "color": "32CD32",
            "is_mini": False,
            "name": "Shaper",
            "side_code": "runner"
        },
        {
            "code": "neutral-runner",
            "color": "808080",
            "is_mini": False,
            "name": "Neutral",
            "side_code": "runner"
        },
        {
            "code": "haas-bioroid",
            "color": "8A2BE2",
            "is_mini": False,
            "name": "Haas-Bioroid",
            "side_code": "corp"
        },
        {
            "code": "jinteki",
            "color": "DC143C",
            "is_mini": False,
            "name": "Jinteki",
            "side_code": "corp"
        },
        {
            "code": "nbn",
            "color": "FF8C00",
            "is_mini": False,
            "name": "NBN",
            "side_code": "corp"
        },
        {
            "code": "weyland-consortium",
            "color": "006400",
            "is_mini": False,
            "name": "Weyland Consortium",
            "side_code": "corp"
        },
        {
            "code": "neutral-corp",
            "color": "808080",
            "is_mini": False,
            "name": "Neutral",
            "side_code": "corp"
        },
        {
            "code": "apex",
            "color": "8C4847",
            "is_mini": True,
            "name": "Apex",
            "side_code": "runner"
        },
        {
            "code": "adam",
            "color": "A79C59",
            "is_mini": True,
            "name": "Adam",
            "side_code": "runner"
        },
        {
            "code": "sunny-lebeau",
            "color": "6E6E6E",
            "is_mini": True,
            "name": "Sunny Lebeau",
            "side_code": "runner"
        }
    ]

    ENTRY = {
        "user_id": 42980,
        "user_name": "Tak",
        "user_import_name": "Tak",
        "rank_swiss": 2,
        "rank_top": 3,
        "runner_deck_title": "92% Solomir's Arissana (3rd @ West Coast Nats)",
        "runner_deck_identity_id": "34020",
        "runner_deck_url": "https://netrunnerdb.com/en/decklist/77500",
        "corp_deck_title": "A Glacial Teia (3rd @ West Coast Nats)",
        "corp_deck_identity_id": "34039",
        "corp_deck_url": "https://netrunnerdb.com/en/decklist/77501",
        "runner_deck_identity_title": "Arissana Rocha Nahu: Street Artist",
        "runner_deck_identity_faction": "shaper",
        "corp_deck_identity_title": "A Teia: IP Recovery",
        "corp_deck_identity_faction": "jinteki"
    }

    TOURNAMENT = {
        "id": 3789,
        "title": "Circuit Opener 2023 #2 in Brno",
        "creator_id": 15340,
        "creator_name": "Krasty",
        "creator_supporter": 1,
        "creator_class": "supporter",
        "created_at": "2023.05.31. 15:11:16",
        "location": "Czechia, Brno-střed",
        "location_lat": 49.178417,
        "location_lng": 16.595302,
        "location_country": "Czechia",
        "location_state": "",
        "address": "Vídeňská 80, 639 00 Brno-střed, Czechia",
        "store": "BLACK OIL – Gaming & Social Hub",
        "place_id": "ChIJnQu_9WmUEkcRtVnjhqAs4u0",
        "contact": "krasty23 (at) gmail.com or just Krasty everywhere else (Discord, Slack, etc.)",
        "approved": 1,
        "registration_count": 9,
        "photos": 0,
        "url": "https://alwaysberunning.net/tournaments/3789/circuit-opener-2023-2-in-brno",
        "link_facebook": "",
        "cardpool": "Parhelion",
        "date": "2023.06.29.",
        "type": "circuit opener",
        "format": "standard",
        "mwl": "Standard Ban List 23.03",
        "concluded": True,
        "charity": False,
        "players_count": 8,
        "top_count": 0,
        "claim_count": 3,
        "claim_conflict": False,
        "matchdata": True,
        "videos": 0,
        "winner_runner_identity": "26066",
        "winner_corp_identity": "21054",
        "rendered_in": 0.6298110485076904,
        "tournament_count": 2837
    }

    LAST_5_TOURNAMENTS = [
        {
            "id": 3777,
            "title": "Connecticut H1 Circuit Opener #1",
            "creator_id": 17403,
            "creator_name": "Banknote",
            "creator_supporter": 0,
            "creator_class": "",
            "created_at": "2023.05.23. 23:59:54",
            "location": "United States, CT, Clinton",
            "location_lat": 41.278846,
            "location_lng": -72.526976,
            "location_country": "United States",
            "location_state": "CT",
            "address": "5 Post Office Square, Clinton, CT 06413, USA",
            "store": "Akiba Underground",
            "place_id": "ChIJZVobqK4o5okRMbszR8xg8vc",
            "contact": "Banknote (Conrad) on GLC",
            "approved": 1,
            "registration_count": 11,
            "photos": 0,
            "url": "https://alwaysberunning.net/tournaments/3777/connecticut-h1-circuit-opener-1",
            "link_facebook": "https://www.facebook.com/events/175964408466261/?ref=newsfeed",
            "cardpool": "Parhelion",
            "date": "2023.07.02.",
            "type": "circuit opener",
            "format": "standard",
            "mwl": "Standard Ban List 23.03",
            "concluded": True,
            "charity": False,
            "players_count": 14,
            "top_count": 0,
            "claim_count": 1,
            "claim_conflict": False,
            "matchdata": True,
            "videos": 0,
            "winner_runner_identity": "26066",
            "winner_corp_identity": "11017",
            "rendered_in": 0.06965088844299316,
            "tournament_count": 2843
        },
        {
            "id": 3782,
            "title": "London H1 CO #2",
            "creator_id": 21954,
            "creator_name": ".Feathermark",
            "creator_supporter": 0,
            "creator_class": "",
            "created_at": "2023.05.28. 15:17:40",
            "location": "United Kingdom, London",
            "location_lat": 51.490544,
            "location_lng": -0.049833000000000016,
            "location_country": "United Kingdom",
            "location_state": "",
            "address": "Silverlock Tenants Hall, Warndon St, London SE16 2SB, UK",
            "store": "Silverlock TRA Hall",
            "place_id": "ChIJs1v5Vx4DdkgR222K3ZMDWWA",
            "contact": "07796474799, nickwilson521@gmail.com",
            "approved": 1,
            "registration_count": 12,
            "photos": 7,
            "url": "https://alwaysberunning.net/tournaments/3782/london-h1-co-2",
            "link_facebook": "",
            "cardpool": "Parhelion",
            "date": "2023.07.02.",
            "type": "circuit opener",
            "format": "standard",
            "mwl": "Standard Ban List 23.03",
            "concluded": True,
            "charity": False,
            "players_count": 12,
            "top_count": 0,
            "claim_count": 2,
            "claim_conflict": False,
            "matchdata": True,
            "videos": 0,
            "winner_runner_identity": "31026",
            "winner_corp_identity": "22050"
        },
        {
            "id": 3786,
            "title": "GENT CO 2023_01",
            "creator_id": 18143,
            "creator_name": "FREDPI",
            "creator_supporter": 0,
            "creator_class": "",
            "created_at": "2023.05.30. 12:12:10",
            "location": "Belgium, Gent",
            "location_lat": 51.037245,
            "location_lng": 3.727036,
            "location_country": "Belgium",
            "location_state": "",
            "address": "Ottergemsesteenweg 13, 9000 Gent, Belgium",
            "store": "Outpost Game Center Ghent",
            "place_id": "ChIJqzM521dxw0cRNVfyYkPzlzU",
            "contact": "",
            "approved": 1,
            "registration_count": 8,
            "photos": 0,
            "url": "https://alwaysberunning.net/tournaments/3786/gent-co-2023-01",
            "link_facebook": "",
            "cardpool": "Parhelion",
            "date": "2023.07.02.",
            "type": "circuit opener",
            "format": "standard",
            "mwl": "Standard Ban List 23.03",
            "concluded": True,
            "charity": False,
            "players_count": 12,
            "top_count": 3,
            "claim_count": 4,
            "claim_conflict": False,
            "matchdata": True,
            "videos": 0,
            "winner_runner_identity": "26066",
            "winner_corp_identity": "22026"
        },
        {
            "id": 3815,
            "title": "Warsaw Circuit Opener (almost) H1 2023: Parhelion",
            "creator_id": 3752,
            "creator_name": "Matuszczak",
            "creator_supporter": 0,
            "creator_class": "",
            "created_at": "2023.06.21. 19:43:42",
            "location": "Poland, Warszawa",
            "location_lat": 52.212317,
            "location_lng": 20.956225,
            "location_country": "Poland",
            "location_state": "",
            "address": "al. Jerozolimskie 179, 02-222 Warszawa, Poland",
            "store": "Graal Blue City",
            "place_id": "ChIJzyFF4uLLHkcRL6625GRftrw",
            "contact": "matthewradecki@gmail.com",
            "approved": 1,
            "registration_count": 3,
            "photos": 0,
            "url": "https://alwaysberunning.net/tournaments/3815/warsaw-circuit-opener-almost-h1-2023-parhelion",
            "link_facebook": "https://www.facebook.com/groups/netrunner.polska",
            "cardpool": "Parhelion",
            "date": "2023.07.02.",
            "type": "circuit opener",
            "format": "standard",
            "mwl": "Standard Ban List 23.03",
            "concluded": True,
            "charity": False,
            "players_count": 5,
            "top_count": 0,
            "claim_count": 0,
            "claim_conflict": False,
            "matchdata": True,
            "videos": 0,
            "winner_runner_identity": "26066",
            "winner_corp_identity": "33057"
        },
        {
            "id": 3771,
            "title": "Singapore 2023 Online Circuit Opener",
            "creator_id": 22484,
            "creator_name": "Ghost00",
            "creator_supporter": 0,
            "creator_class": "",
            "created_at": "2023.05.17. 15:57:58",
            "location": "online",
            "location_lat": None,
            "location_lng": None,
            "location_country": "",
            "location_state": "",
            "address": "",
            "store": "",
            "place_id": "ChIJzVHFNqkZ2jERboLN2YrltH8",
            "contact": "derekyang8@gmail.com",
            "approved": 1,
            "registration_count": 11,
            "photos": 0,
            "url": "https://alwaysberunning.net/tournaments/3771/singapore-2023-online-circuit-opener",
            "link_facebook": "",
            "cardpool": "Parhelion",
            "date": "2023.07.01.",
            "type": "circuit opener",
            "format": "standard",
            "mwl": "Standard Ban List 23.03",
            "concluded": True,
            "charity": False,
            "players_count": 12,
            "top_count": 0,
            "claim_count": 7,
            "claim_conflict": False,
            "matchdata": True,
            "videos": 0,
            "winner_runner_identity": "26066",
            "winner_corp_identity": "33057"
        }
    ]
